export CUDA_VISIBLE_DEVICES=0

model_name=TimePerceiver

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.csv \
  --model_id solar_384_96 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 384 \
  --label_len 0 \
  --pred_len 96 \
  --enc_in 137 \
  --des 'Exp' \
  --d_model 512 \
  --d_ff 1024 \
  --itr 1 \
  --num_latents 32 \
  --latent_dim 128 \
  --latent_d_ff 256 \
  --dropout 0.2 \
  --generalized 1 \
  --standard 0 \
  --use_latent 1 \
  --num_latent_blocks 1 \
  --patch_len 16 \
  --batch_size 32 \
  --n_heads 8 \
  --separate_ratio 0

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.csv \
  --model_id solar_384_192 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 384 \
  --label_len 0 \
  --pred_len 192 \
  --enc_in 137 \
  --des 'Exp' \
  --d_model 512 \
  --d_ff 1024 \
  --itr 1 \
  --num_latents 32 \
  --latent_dim 128 \
  --latent_d_ff 256 \
  --dropout 0.2 \
  --generalized 1 \
  --standard 0 \
  --use_latent 1 \
  --num_latent_blocks 1 \
  --patch_len 16 \
  --batch_size 64 \
  --n_heads 8 \
  --separate_ratio 0

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.csv \
  --model_id solar_384_336 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 384 \
  --label_len 0 \
  --pred_len 336 \
  --enc_in 137 \
  --des 'Exp' \
  --d_model 512 \
  --d_ff 1024 \
  --itr 1 \
  --num_latents 32 \
  --latent_dim 128 \
  --latent_d_ff 256 \
  --dropout 0.2 \
  --generalized 1 \
  --standard 0 \
  --use_latent 1 \
  --num_latent_blocks 1 \
  --patch_len 16 \
  --batch_size 64 \
  --n_heads 8 \
  --separate_ratio 0

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.csv \
  --model_id solar_384_720 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 384 \
  --label_len 0 \
  --pred_len 720 \
  --enc_in 137 \
  --des 'Exp' \
  --d_model 512 \
  --d_ff 1024 \
  --itr 1 \
  --num_latents 32 \
  --latent_dim 128 \
  --latent_d_ff 256 \
  --dropout 0.2 \
  --generalized 1 \
  --standard 0 \
  --use_latent 1 \
  --num_latent_blocks 1 \
  --patch_len 16 \
  --batch_size 32 \
  --n_heads 8 \
  --separate_ratio 0